// 
// Name: Exceptions.cpp : implementation file 
// Author: hieunt
// Description: Handle exceptions in this application
//

#pragma once 

// Handle error in program

/* Enumeration of errors */
typedef enum {
	SUCCESS = 0,

	/* Errors */ 
	ERR_CANNOT_GET_FILE_SIZE,
	ERR_SORT_MERGE_FILE_NOT_ENOUGH,
	ERR_NOT_ENOUGH_MEMORY,
	ERR_NOT_INIT_MEMORY,
	ERR_CANNOT_INITIAL_MEMORY,
	ERR_CANNOT_INITIAL_BUFFER_POOL,
	ERR_CANNOT_CREATE_HANDLE,
	ERR_END_OF_FILE,
	ERR_SORT_EMPTY_BUFFER,
	ERR_INVALID_COMMAND_LINE_PARAMETERS,
	ERR_SORT_CANNOT_ASYNC_READ,
	ERR_UNKNOWN_EXCEPTION,
	ERR_CANNOT_GET_TUPLE_KEY,
	ERR_WMI_FAILED_TO_INITIALIZE_COM_LIBRARY,
	ERR_WMI_FAILED_TO_INITIALIZE_SECURITY,
	ERR_WMI_FAILED_TO_CREATE_IWBEMLOCATOR_OBJECT, 
	ERR_WMI_COULD_NOT_CONNECT_WMI_NAMESPACE,
	ERR_WMI_COULD_NOT_SET_PROXY_BLANKET,
	ERR_WMI_QUERY_FAILED,
	ERR_WMI_NOT_FOUND_ANY_INSTANCE,
	ERR_SMJ_INIT_PARAM_FAILED 
} RC;

LPWSTR PrintErrorRC(RC rc);
 
